fronturl:
  "http://ktbpractice-hongday.n-e.kr:80"

backurl:
  "http://ktbpractice-hongday.n-e.kr:80"

spring:
  datasource:
    url: jdbc:mysql://week9-infra-db.ctmm2cyosp8o.ap-northeast-2.rds.amazonaws.com:3306/ktbpractice?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dayday328