fronturl:
  "https://ktbpractice-hongday.n-e.kr:80"

backurl:
  "https://ktbpractice-hongday.n-e.kr:80"

spring:
  datasource:
    url: jdbc:mysql://3.38.94.43:3306/ktbpractice?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dayday