fronturl:
  "http://localhost:3000"

backurl:
  "http://localhost:8080"

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ktbpractice?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dayday